/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package waitinglinesimulation;

/**
 *
 * @author user
 */
public class Case1 extends javax.swing.JFrame {

    /**
     * Creates new form Case1
     */
    public Case1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel2 = new javax.swing.JPanel();
        L = new javax.swing.JLabel();
        W = new javax.swing.JLabel();
        Lq = new javax.swing.JLabel();
        Wq = new javax.swing.JLabel();
        P0 = new javax.swing.JLabel();
        P = new javax.swing.JLabel();
        case1 = new javax.swing.JLabel();
        jLabel_L = new javax.swing.JLabel();
        jLabelWQ = new javax.swing.JLabel();
        jLabelP = new javax.swing.JLabel();
        jLabel_W = new javax.swing.JLabel();
        jLabel_Lq = new javax.swing.JLabel();
        jLabelP0 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel2.setBackground(new java.awt.Color(0, 153, 153));
        Panel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        L.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        L.setText("L");

        W.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        W.setText("W");

        Lq.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Lq.setText("Lq");

        Wq.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Wq.setText("Wq ");

        P0.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        P0.setText("P0");

        P.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        P.setText("P");

        case1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        case1.setText("CASE 1");

        jLabel_L.setText("jLabel1");

        jLabelWQ.setText("jLabel2");

        jLabelP.setText("jLabel3");

        jLabel_W.setText("jLabel4");

        jLabel_Lq.setText("jLabel5");

        jLabelP0.setText("jLabel7");

        javax.swing.GroupLayout Panel2Layout = new javax.swing.GroupLayout(Panel2);
        Panel2.setLayout(Panel2Layout);
        Panel2Layout.setHorizontalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(case1))
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(W, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lq))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Lq)
                            .addComponent(jLabel_W)
                            .addComponent(jLabel_L, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Wq)
                            .addComponent(P)
                            .addComponent(P0))
                        .addGap(77, 77, 77)
                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelP0)
                            .addComponent(jLabelP)
                            .addComponent(jLabelWQ, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(231, Short.MAX_VALUE))
        );

        Panel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {L, Lq, P, P0, W, Wq});

        Panel2Layout.setVerticalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(case1)
                .addGap(52, 52, 52)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L)
                    .addComponent(Wq)
                    .addComponent(jLabel_L, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelWQ, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lq)
                            .addComponent(P0)
                            .addComponent(jLabel_Lq)
                            .addComponent(jLabelP0)))
                    .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(W)
                        .addComponent(P)
                        .addComponent(jLabelP)
                        .addComponent(jLabel_W)))
                .addContainerGap(201, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Case1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Case1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Case1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Case1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Case1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L;
    private javax.swing.JLabel Lq;
    private javax.swing.JLabel P;
    private javax.swing.JLabel P0;
    private javax.swing.JPanel Panel2;
    private javax.swing.JLabel W;
    private javax.swing.JLabel Wq;
    private javax.swing.JLabel case1;
    public javax.swing.JLabel jLabelP;
    public javax.swing.JLabel jLabelP0;
    public javax.swing.JLabel jLabelWQ;
    public javax.swing.JLabel jLabel_L;
    public javax.swing.JLabel jLabel_Lq;
    public javax.swing.JLabel jLabel_W;
    // End of variables declaration//GEN-END:variables
}
